"""add item.owner (fix IDOR)

Revision ID: 4640d1c2f368
Revises: b1172a509f07
Create Date: 2026-07-02 00:39:41.245380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4640d1c2f368'
down_revision: Union[str, None] = 'b1172a509f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_items_owner'), ['owner'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_owner'))
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
